#!/usr/bin/env node

const yargs = require("yargs");
const { launch } = require("../src/index");

const cliParser = yargs
  .usage("Usage: puppeteer-worker")
  .option("rabbitmq", {
    describe: "the rabbitmq connection string",
    type: "string",
  })
  .option("import-prefix", {
    type: "string",
    description: "import prefix string from jobDir",
    default: "../../",
  })
  .option("m", {
    alias: "mode",
    type: "string",
    default: "default",
    choices: ["default", "headless", "visible", "docker"],
    describe: "The puppeteer mode",
  })
  .option("log-dest", {
    type: "string",
    default: "cs",
    choices: ["cs", "fs"],
  })
  .option("log-dir", {
    type: "string",
    default: "./logs/",
  })
  .option("job-dir", {
    type: "string",
    default: "./jobs/",
  })
  .option("tmp-dir", {
    type: "string",
    default: "./tmp/",
  })
  .option("max-try", {
    type: "number",
    default: 10,
  });
const options = cliParser.argv;

async function main() {
  const puppeteerWorker = await launch({
    tmpDir: options.tmpDir, // tmp dir currently not used yet
    logDest: options.logDest, // "fs" or "cs"
    logDir: options.logDir,
    secret: options.secret,
    jobDir: options.jobDir,
    jobImportPrefix: options.importPrefix, // the relative path from job-template.db.js
    rabbitmqConnectionString: options.rabbitmq,
    maxTry: options.maxTry,
    puppeteerMode: options.mode, // "default", "headless", "visible", "docker"
  });

  // puppeteerWorker.http().start();
  puppeteerWorker.amqp().start();
}

main();
